### ISSUE TITLE
Role page doesn't show the other mafias to the player

### ISSUE THREAD

**Issue by ctyar** [samanrashidii/mafiabuzz#223]
I think on this page the app should show the names of all the mafia players. They all should know each other when the game starts.

![Screenshot_2020-03-18 MafiaBuzz Creator](https://user-images.githubusercontent.com/1432648/76963635-90665f00-6936-11ea-9b71-395b5dbaee50.png)

**Comment by samanrashidii** [comment]
Hi ctyar,

Thanks for opening this issue. Unfortunately, we can't do it because it's a rule of Mafia game that during the first night all mafias should open their eyes and see each other.
![Screenshot](https://user-images.githubusercontent.com/19384380/77247336-bbf68b80-6c4d-11ea-9edf-4eada02394e9.png)

**Comment by ctyar** [comment]
So basically you are starting the game with a day but that's not the only way to play the game.
A lot of people start the game in a night. Sometimes a special kind of night that only contains mafias knowing each other with no kills.
From [Wikipedia](https://en.wikipedia.org/wiki/Mafia_%28party_game%29#Gameplay):

> At the start of the game, every werewolf is given the identities of their teammates, whereas the innocents only receive the number of werewolves in the game, and do not know which players are werewolves and which are villagers. 

I think this could be an option to support both starting with a day and a night.

**Comment by samanrashidii** [comment]
Yes, I got what you say and talked to our game designer. We found there is an issue with this approach, some of our users are playing this game with group of 40-50 people and they have a minimum of 15-20 mafias in each game. During the show character phase, each person looks at his role and pass the phone to the next person. If each mafia has to read every 15 people's names and remember them, it will take more time for the person and will reveal his mafia identity to the people because citizens don't have this option. So it should be handled by the game god or moderator. Even if they want to start the game from the day phase, they should all close their eyes and let mafia see each other before starting the game.
